Website/Website/Documents/urls.py
from django.conf.urls import url
from . import views


app_name = 'Documents'

urlpatterns = [
    # Documents/main/search/assetEdit/
    url(r'^main/search/assetEdit/(?P<pk>[0-9]+)/$', views.AssetEditView.as_view(), name='assetEdit'),
    
    # Documents/main/search/documentEdit/
    url(r'^main/search/documentEdit/(?P<pk>[0-9]+)/$', views.DocumentEditView.as_view(), name='documentEdit'),
    # Documents/main/assetCreate
    url(r'^main/assetCreate/$', views.AssetCreate.as_view(), name='assetCreate'),
    # Documents/main/docCreate
    url(r'^main/docCreate/$', views.DocCreate.as_view(), name='docCreate'),
    # Documents/main/search
    url(r'^main/search/$', views.Search.as_view(), name='search'),
    # Documents/login/
    url(r'^login/$', views.UserFormView.as_view(), name='login'),
    # Documents/logoutuser/
    url(r'^logoutuser/$', views.logoutuser, name='logout'),
    # Documents/main/
    url(r'^main/$', views.MainPage.as_view(), name='main'),
    # Documents/main/search/docDetail
    url(r'^main/search/docDetail/(?P<pk>[0-9]+)/$', views.DocDetail.as_view(), name='docDetail'),
    
]

Website/Website/Website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Documents/', include('Documents.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/Website/Documents/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime

StatusChoices = (
    (None, "-----"),
    ("Active", "Active"),
    ("Sold", "Sold")
)

class ApprovalAgency(models.Model):
    approval_agency = models.CharField(max_length = 500)
    
    def __str__(self):
        return self.approval_agency


class AssetType(models.Model):
    approval_agency = models.ForeignKey(ApprovalAgency)
    asset_type = models.CharField(max_length = 500)
    
    def __str__(self):
        return self.asset_type

class DocumentType(models.Model):
    document_type = models.CharField(max_length = 500)
    document_type_desc = models.CharField(max_length = 500, blank = True)
    
    def __str__(self):
        return self.document_type + " " + self.document_type_desc
        
class Asset(models.Model):
    approval_agency = models.ForeignKey(ApprovalAgency)
    asset_type = models.ForeignKey(AssetType)
    manufacture_name = models.CharField(max_length = 500, blank = True)
    serial_number = models.CharField(max_length = 500)
    tag_number = models.CharField(max_length = 500, blank = True)
    status = models.CharField(max_length = 500, choices = StatusChoices, blank =True)
    
    def get_absolute_url(self):
        return reverse('Documents:assetCreate')
    
    def __str__(self):
        return str("serial number: " + self.serial_number + " , tag number: " + self.tag_number)

class Document(models.Model):
    asset = models.ManyToManyField(Asset, blank=True)
    document_type = models.ForeignKey(DocumentType)
    document_date = models.DateField()
    renewal_date = models.DateField(blank = True, null=True)
    a_number = models.CharField(max_length = 500, blank = True)
    license_decal_number = models.CharField(max_length = 500, blank = True)
    model_number = models.CharField(max_length = 500, blank = True)
    document_description = models.CharField(max_length = 500, blank = True)
    document_file = models.FileField(upload_to='uploads/%Y/%m/%d/')
    
    def get_absolute_url(self):
        return reverse('Documents:docCreate')
    
    def __str__(self):
        return  str(self.id) + " " + str(self.document_date) + " " + str(self.renewal_date) + " " + str(self.a_number) + " " + str(self.license_decal_number) + " " + str(self.model_number) + " " +str(self.document_description)

class OCRCoordinates(models.Model):
    document_type = models.ForeignKey(DocumentType)
    document_date_left = models.CharField(max_length = 500)
    
    document_date_top = models.CharField(max_length = 500)
    document_date_right = models.CharField(max_length = 500)
    
    document_date_bottom = models.CharField(max_length = 500)
    document_date_letterset = models.CharField(max_length = 500, blank = True)
    document_date_Regex = models.CharField(max_length = 500, blank = True)
    
    document_date_MarkingType = models.CharField(max_length = 500, blank = True)
    locument_date_texttype = models.CharField(max_length = 500, blank = True)
    
    license_decal_left = models.CharField(max_length = 500)
    license_decal_top = models.CharField(max_length = 500)
    license_decal_right = models.CharField(max_length = 500)
    license_decal_bottom = models.CharField(max_length = 500)
    license_decal_letterset = models.CharField(max_length = 500, blank = True)
    license_decal_Regex = models.CharField(max_length = 500, blank = True)
    license_decal_Markingtype = models.CharField(max_length = 500, blank = True)
    license_decal_texttype = models.CharField(max_length = 500, blank = True)
    
    renewal_date_left = models.CharField(max_length = 500)
    renewal_date_top = models.CharField(max_length = 500)
    renewal_date_right = models.CharField(max_length = 500)
    renewal_date_bottom = models.CharField(max_length = 500)
    renewal_date_letterset = models.CharField(max_length = 500, blank = True)
    renewal_date_regex = models.CharField(max_length = 500, blank = True)
    renewal_date_texttype = models.CharField(max_length = 500, blank = True)
    
    def __str__(self):
        return str(self.id) + " " + str(self.document_type) + " " + str(self.document_date_top)

Website/Website/Documents/views.py
import os
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from .form import AssetCreateForm, DocCreateForm, UserForm, AssetSearchForm, DocSearchForm, AssetLinkForm, DocEditForm
from .models import Asset, Document
from django.http import HttpResponse
import json, datetime
from .data_access import SearchQuery, ObjectCreate, ObjectUpdate, OCRExtract, UserActivityLog
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
import ocrizer

# Control view of assetEdit.html
@method_decorator(login_required, name='dispatch')
class AssetEditView(UpdateView):

    model = Asset
    fields = ['approval_agency', 'asset_type', 'manufacture_name', 'serial_number', 'tag_number', 'status']
    template_name = 'Documents/assetEdit.html'
    
    # Render the search.html page after clicking update the asset
    def get_success_url(self):
        UserActivityLog().logUserActivity(self.request.user.username, "Asset Changed")  
        return reverse_lazy('Documents:search')

# Control view of documentEdit.html
@method_decorator(login_required, name='dispatch')
class DocumentEditView(UpdateView):

    model= Document
    form_class = DocEditForm
    second_form_class = AssetLinkForm
    template_name = 'Documents/documentEdit.html'

    # override get_context_data, send more forms to the front end besides basic form_class
    def get_context_data(self, **kwargs):
        
        # get asset objects linked with current object
        asset_objects = SearchQuery().searchLinkedAssetsByDocumentId(self.object)
        
        # get form_class of current document
        context = super(DocumentEditView, self).get_context_data(**kwargs)
        
        # add extra forms to context
        context['asset_link_form'] = self.second_form_class(self.request.GET)        
        context['document_type_object'] = self.object.document_type
        context['asset_objects'] = asset_objects
        return context

    # listen different front end request, query from database, send it back with http response
    def post(self, request, *args, **kwargs):
        
        # get current document object
        self.object = self.get_object()
        
        # request that search asset
        if request.POST.get('search_type'):
            attributeList = ['approval_agency', 'serial_number', 'tag_number']            
            return SearchQuery().searchAssetOrDocumentObjects(request, attributeList, 'asset_search')
        
        # request that updating document object
        elif request.POST.get('document_date'):
            ObjectUpdate().updateObject(request, self.object)
            UserActivityLog().logUserActivity(self.request.user.username, "Document Changed") 
            return redirect('Documents:search')
        
        # request that searching document type
        elif request.POST.get("document_type"):
            return SearchQuery().searchDocumentTypeByAutoComplete(request.POST.get("document_type"))
      
    # useless function, already done by redirect                          
    def get_success_url(self):
        UserActivityLog().logUserActivity(self.request.user.username, "Document Changed") 
        return reverse_lazy('Documents:search')

# Control view of loginPage.html
class UserFormView(View):
    
    form_class = UserForm
    template_name = 'Documents/loginPage.html'
    
    # send user form when page is loading
    def get(self, request):        
        form = self.form_class(None)        
        return render(request, self.template_name, {'form': form})
    
    # check username and password when login, redirect to main page if successful
    def post(self, request):        
        form = self.form_class(None)
        username = request.POST.get('username')
        password = request.POST.get('password')                    
        user = authenticate(username=username, password=password)     
           
        if user is not None:            
            if user.is_active:       
                UserActivityLog().logUserActivity(username, 'login')           
                login(request, user)                
                return redirect('Documents:main')   
        else:    
            login_invalid = 'login is invalid, username or password is wrong'        
            return render(request, self.template_name, {'form': form, 'error_message' :login_invalid})

# Control view of assetCreate.html
@method_decorator(login_required, name='dispatch')
class AssetCreate(CreateView):
    
    form_class = AssetCreateForm
    template_name = 'Documents/assetCreate.html'
    
    # override get method implementing from CreateView, request that searching for approval agency
    def get(self, request, *args, **kwargs):       
        if request.GET.get('approval_agency'):                        
            return SearchQuery().searchAssetTypesByApprovalAgency(request.GET.get('approval_agency'))        
        self.object = None
        return super(CreateView, self).get(request, *args, **kwargs)
    
    # override post method implementing from CreateView, create activity log after submitting form
    def post(self, request, *args, **kwargs):
        
        UserActivityLog().logUserActivity(request.user.username, "Asset Create Completed")   
        
        return CreateView.post(self, request, *args, **kwargs)
 
# Control view of docCreate.html   
@method_decorator(login_required, name='dispatch')
class DocCreate(View):
    coordinate_result = ""
    document_file_name = ""
    
    docform_class = DocCreateForm
    asset_link_form_class = AssetLinkForm
    template_name = 'Documents/docCreate.html'
    
    # override get method implementing from View, send forms to front end
    def get(self, request):        
        docform = self.docform_class(None)
        asset_link_form = self.asset_link_form_class(None)       
        return render(request, self.template_name, {'docform' : docform, 'asset_link_form' : asset_link_form})
    
    # save uploaded file for OCR  
    def handle_uploaded_file(self, f):
        with open('testfile.pdf', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
                
    # override get method implementing from View
    def post(self, request):  
                
        # request that creating a new document object
        if request.POST.get("document_date"):   
            UserActivityLog().logUserActivity(request.user.username, "Document Create Completed")   
            ObjectCreate().documentObjectCreate(request)                              
            return self.get(request)
        
        # request that uploading a document file for OCR
        elif request.POST.get("document_file_entry") :
            self.handle_uploaded_file(request.FILES['document_file_entry'])
            self.document_file_name = os.getcwd() + '/testfile.pdf'
            return self.runOCR()
        
        # request that finding OCR Coordinates by document type
        elif request.POST.get("document_type_id"):
            self.coordinate_result = SearchQuery().searchOCRCoordinatesByDocumentType(request.POST.get("document_type_id"))
            return self.runOCR()
            
        # request that searching document type
        elif request.POST.get("document_type"):
            return SearchQuery().searchDocumentTypeByAutoComplete(request.POST.get("document_type"))
            
        # request that search assets 
        elif self.request.POST.get("search_type"):
            attributeList = ['approval_agency', 'serial_number', 'tag_number']            
            return SearchQuery().searchAssetOrDocumentObjects(request, attributeList, 'asset_search')
    
    # run OCR and return value when coordinate and document file is ready
    def runOCR(self):
        if self.coordinate_result and self.document_file_name: 
            return OCRExtract().getDocumentValuesByOCR(self.coordinate_result, self.document_file_name)
        else:
            return HttpResponse(json.dumps("Error"), content_type="application/json")
        
# Control view of search.html
@method_decorator(login_required, name='dispatch')
class Search(View):
    
    assetform_class = AssetSearchForm
    docform_class = DocSearchForm
    template_name = 'Documents/search.html'
        
    def get(self, request):
        
        # request that searching for approval agency
        if request.GET.get('approval_agency'):                        
            return SearchQuery().searchAssetTypesByApprovalAgency(request.GET.get('approval_agency'))
                                    
        # request that searching for document
        elif request.GET.get('asset_id'):            
            return SearchQuery().searchDocumentsByAssetId(request.GET.get('asset_id'))
           
        # render the search.html page 
        else:   
            flag = getUserType() 
            assetform = self.assetform_class(None)
            docform = self.docform_class(None)
            
            return render(request, self.template_name, {'assetform': assetform, 'docform' : docform, 'flag': flag})         
            
    
    def post(self, request):  
        
        # request that searching asset and document
        if request.POST.get('search_type'):      
            if(request.POST.get('search_type') == 'asset_search'):     
                UserActivityLog().logUserActivity(request.user.username, "Asset Search")            
                attributeList = ['approval_agency', 'asset_type', 'status']                
                return SearchQuery().searchAssetOrDocumentObjects(request, attributeList, 'asset_search')
            

Website/Website/Documents/templates/Documents/asset-selected-table-template.html
<div class="form-group" style="margin-left: 25px">
	<div class="col-sm-10" id="asset_selected_table_parent">
		<table class="table" id="asset_selected_table" class="col-sm-12">
			<thead>
				<tr>
					<th>#</th>
					<th>Approval_agency</th>
					<th>Serial_number</th>
					<th>Tag_number</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody id="asset_link_selected">
			</tbody>
		</table>
	</div>
</div>

Website/Website/Documents/templates/Documents/assetCreate.html
{% extends 'Documents/base.html' %} {% block body %}

<!-- Content Section -->
<section>
	<div class="container">
		<div class="row row-content">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a
					href=" {% url 'Documents:main' %}">Main Page</a></li>
				<li class="breadcrumb-item active">Asset Create</li>
			</ol>
		</div>
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<h3>Create Asset</h3>
				<hr>
				<form class="form-horizontal" action="" method="post">
					{% csrf_token %} 
					{% for field in form %}
					{% if field == form.approval_agency or field == form.asset_type or field == form.serial_number %}
                    <div class="form-group">
						<label class="control-label col-sm-4">{{field.label_tag}} *</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% else %}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<span class="text-danger small">{{ field.errors }}</span>
						</div>
						<label class="control-label col-sm-4">{{ field.label_tag}}</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% endif %}
					{% endfor %}
					<div class="form-group" style="margin-left: 40px"">
						<button id="asset_create_submit_button" type="submit"
							class="btn btn-success">Save</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>

<script>
	$('#id_approval_agency').change(function() {
		getForAsset('#id_approval_agency', '#id_asset_type');
	});

	$("#asset_create_submit_button").click(function(event) {
		return showConfirmationBox("Asset");
	});
	
</script>

{% endblock %}

Website/Website/Documents/templates/Documents/docCreate.html
{% extends 'Documents/base.html' %} {% block body %}
<!-- Content Section -->
<section>
	<div class="container">
		<div class="row row-content">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a
					href=" {% url 'Documents:main' %}">Main Page</a></li>
				<li class="breadcrumb-item active">Document Create</li>
			</ol>
		</div>
		<div class="row row-content">
			<div class="col-sm-12 col-md-7">
				<h3>Create Document</h3>
				<hr>
				<form class="form-horizontal" action="" method="post"
					id="document_create_form" enctype="multipart/form-data">
					{% csrf_token %} 
					{% for field in docform %} 
					{% if field == docform.document_type %}
					<div class="form-group">
						<label class="control-label col-sm-4">{{field.label_tag}} *</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					<div class="warning" style="display: none">
						<p>Please enter the document type</p>			
					</div>
					{% elif field == docform.document_date %}
					<div class="form-group">
                        <label class="control-label col-sm-4">{{field.label_tag}} *</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% else %}
					<div class="form-group">
						<label class="control-label col-sm-4">{{field.label_tag}}</label>
						<div class="col-sm-8">{{ field }}</div>
					</div>
					{% endif %} 
				    {% endfor %} 
					{% include 'Documents/asset-selected-table-template.html' %}
					<div class="form-group hidden" style="margin-left: 40px">
						<label class="control-label col-sm-4"> document type id:</label>
						<div class="col-sm-8">
							<input id="document_type_id" name="document_type_id">
						</div>
					</div>
					<div class="form-group hidden" style="margin-left: 40px"">
						<label class="control-label col-sm-2"> asset id:</label>
						<div class="col-sm-10">
							<input id="asset_id" name="asset_id">
						</div>
					</div>
					<br> <br>
					<div class="form-group" style="margin-left: 40px">
						<button id="document_create_submit_button" type="submit"
							class="btn btn-success">Save</button>
					</div>
				</form>
			</div>
			{% include 'Documents/asset-link-form-template.html' %}
		</div>
		<div class="modal fade" id="ocr_progress" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
		  <div class="modal-dialog modal-sm">
		    <div class="modal-content">
		      <div class="modal-header">
		          <h4>Processing OCR...</h4>
		      </div>
		      <div class="modal-body">
		        <div class="progress">
		          <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
		          </div>
		        </div>
		      </div>
		    </div>
		  </div>
        </div>
	</div>
</section>

<script>
    $(document).ready(function() {
        $('#id_document_date, #id_renewal_date').datepicker({
    	    dateFormat: "yy-mm-dd"
        });
    });


	$('#id_document_type').keyup(function() {
		postForAutoCompleteSearch('#id_document_type');
	});

	$('#id_document_type').focusout(function() {
		var document_type_text = $(this).val();
        var document_type_id = $('#document_type_id').val();
	    if(checkDocumentTypeValid(document_type_text, document_type_id, 'document_create')) {
	    	//postForOCRCoordinate('#document_type_id');
	    }
	});
	
	$('#id_document_file').click(function() {
	})
	
	$("#id_document_file").change(function() {
		$('#ocr_progress').modal('show');
		var formData = new FormData();
		// Attach file
		formData.append('document_file_entry', $('input[type=file]')[0].files[0]); 
		formData.append('document_type_for_ocr', $('#document_type_id').val());
		postForOCR(formData);
	}); 

	$('#asset_link_form').on('submit', function(event) {
		event.preventDefault();
		postForSearch('#asset_link_form', 'asset_link_table_parent');
	});

	$('#asset_selected_table').on('click', 'input[type="button"]',function(event) {
		$(this).closest('tr').remove();
    });
	
	$('#asset_link_table').on('click', 'input[type="button"]',function(event) {
		setAssetSelectedTableData(this);
    });

	$("#document_create_submit_button").click(function(event) {
		return showConfirmationBox("document");
	});
	

</script>
{% endblock %}

Website/Website/Documents/templates/Documents/loginPage.html
{% extends 'Documents/base.html' %} 

{% block link %}href="{% url 'Documents:login' %}"
{% endblock %}
{% block body %}

<!-- Content Section -->
<section>
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<h3>Login</h3> 
                {{error_message}}				
				<hr>
				<form class="form-horizontal" action="" method="post">
				{% csrf_token %}
				{% include 'Documents/form-template.html' %}					
					<div class="form-group" style="margin-left:40px"">
						<button type="submit" class="btn btn-success">Login</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock %}

Website/Website/Documents/templates/Documents/search.html
{% extends 'Documents/base.html' %} {% block body %}
<!-- Content Section -->
<section>
	<div class="container">
	    <div class="row row-content">
			<ol class="breadcrumb">
				<li	class="breadcrumb-item">
					<a href=" {% url 'Documents:main' %}">Main Page</a>
				</li>
				<li	class="breadcrumb-item active">
					Search
				</li>
			</ol>
		</div>
		<div class="row row-content">
			<ul class="nav nav-tabs">
				<li class="active" id="document_search_tab"><a
					href="#document_search" data-toggle="tab"><h4>Document Search</h4></a></li>
				<li id="asset_search_tab"><a href="#asset_search"
					data-toggle="tab">
						<h4>Asset Search</h4>
				</a></li>
			</ul>
			<div class="tab-content">
				<div>
					<p style="padding: 20px;"></p>
				</div>
				<div class="tab-pane fade" id="asset_search">
					<form class="form-horizontal" action="" method="post"
						id="asset_data">
						{% csrf_token %} {% for field in assetform %}
						<div class="form-group">
							{% if field.label_tag == 'document_type' %}
							<div class="ui-widget">
								<label for="tags">{{ field.label_tag }}</label>
								<div class="col-sm-10">{{ field }}</div>
							</div>
							{% endif %} <label class="control-label col-sm-2">
								{{field.label_tag}}</label>
							<div class="col-sm-10">{{ field }}</div>
						</div>
						{% endfor %}
						<div class="form-group hidden">
							<label class="control-label col-sm-2"> asset_search</label>
							<div class="col-sm-10">
								<input name="search_type" value="asset_search">
							</div>
						</div>
						<div class="form-group" style="margin-left: 40px"">
							<button type="submit" class="btn btn-success">Search</button>
						</div>
					</form>
				</div>
				<div class="tab-pane fade in active" id="document_search">
					<form class="form-horizontal" action="" method="post"
						id="document_data">
						{% csrf_token %} {% for field in docform %}
						<div class="form-group">
							<label class="control-label col-sm-2">{{field.label_tag}}</label>
							<div class="col-sm-10">{{ field }}</div>
						</div>
						{% endfor %}
						<div class="form-group hidden" style="margin-left: 40px"">
						    <label class="control-label col-sm-2"> document type id:</label>
							<div class="col-sm-10">
							    <input id="document_type_id" name="document_type_id">
							</div>
					    </div>
						<div class="form-group hidden">
							<label class="control-label col-sm-2"> document_search</label>
							<div class="col-sm-10">
								<input name="search_type" value="document_search">
							</div>
						</div>
						<div class="form-group" style="margin-left: 40px"">
							<button type="submit" class="btn btn-primary">Search</button>
						</div>
					</form>
				</div>
			</div>
			<div>
				<p style="padding: 20px;"></p>
			</div>
		</div>
		<div id="not_found" style="display: none">
			<p>No result found.</p>
		</div>
		<div class="row row-content">
			<div id="asset_table_parent" style="display: none">
					<div>
						<a href="#" class="glyphicon glyphicon-file" id="asset_to_csv"></a>
					</div>
					<table class="table">
						<thead>
							<tr>
								<th>Edit</th>
								<th>#</th>
								<th>Approval_agency</th>
								<th>Asset_type</th>
								<th>Manufacture_name</th>
								<th>Serial_number</th>
								<th>Tag_number</th>
								<th>Status</th>
							</tr>
						</thead>
						<tbody>

						</tbody>
					</table>
			</div>
			<div id="document_table_parent" style="display: none">
				<div>
					<a href="#" class="glyphicon glyphicon-file" id="document_to_csv"></a>
				</div>
				<table class="table">
					<thead>
						<tr>
							<th>Edit</th>
							<th>View File</th>
							<th>Document_type</th>
							<th>Document_date</th>
							<th>Renewal_date</th>
							<th>A_number</th>
							<th>License_decal_number</th>
							<th>Model_number</th>
							<th>Document_description</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>


<script>
    $(document).ready(function() {
        $('#id_document_date, #id_renewal_date_start, #id_renewal_date_end').datepicker({
        	dateFormat: "yy-mm-dd"
        });
    });
    
	$('#asset_data').on('submit', function(event) {
		event.preventDefault();
		postForSearch('#asset_data', 'asset_table_parent');
	});
	
	$('#document_data').on('submit', function(event) {
		event.preventDefault();
		var document_type_text = $('#id_document_type').val();
        var document_type_id = $('#document_type_id').val();
	    checkDocumentTypeValid(document_type_text, document_type_id, 'document_search');
		postForSearch('#document_data', 'document_table_parent');
	});
	
	$('#asset_search_tab').click(function(event) {
		$('#document_table_parent').css('display','none');
	});
	
	$('#document_search_tab').click(function(event) {
		$('#asset_table_parent').css('display','none');
	});
	
	$('#asset_to_csv').click(function(event) {
		postForLog("asset table download");
		var outputFile = 'export';
		outputFile = outputFile.replace('.csv', '') + '.csv';
		exportTableToCSV.apply(this, [$('#asset_table_parent > table'), outputFile ]);
	});
	
	$('#document_to_csv').click(function(event) {
		postForLog("asset table download");
		var outputFile = 'export';
		outputFile = outputFile.replace('.csv', '') + '.csv';
		exportTableToCSV.apply(this, [$('#document_table_parent > table'), outputFile ]);
	});
	
	$('#id_approval_agency').change(function() {
		getForAsset('#id_approval_agency', '#id_asset_type');
	});
	
	$('#id_document_type').keyup(function() {
		postForAutoCompleteSearch('#id_document_type');
	
	});
	
	$(document).on(
		'click',
		'.edit-asset',
		function(event) {
			postForLog("Edit Asset");
			var asset_id = $(event.target).closest('tr').children('td:first').text();
			window.location.href = "assetEdit/" + asset_id;
        });
	
	$(document).on(
		'click',
		'.edit-document',
		function(event) {
			postForLog("Edit Document");
			var document_id = $(event.target).closest('tr').children('td:first').text();
			window.location.href = "documentEdit/" + document_id;
        });
    
	$(document).on(
		'click',
		'#document_id',
		function(event) {
			postForLog("Document File Viewed");
			var document_id = $(event.target).text();
			window.location.href = "docDetail/" + document_id;
        });
	
	$(document).on(
		'click',
		'td',
		function(event) {
			if(event.target.parentElement.hasAttribute('data-toggle')) {
				event.preventDefault();
				return;
			}
			event.preventDefault();
			var data_table_parent = event.target.parentElement;
			asset_id_dict = {asset_id : $(event.target).text()};
			getForDocument(asset_id_dict, data_table_parent);
        });

</script>

{% endblock %}